--PROCEDIMIENTO PARA REGISTRAR DETALLE DEL PEDIDO
DELIMITER ;;
CREATE PROCEDURE `REGISTRAR_DETALLE_PEDIDO`(
    IN PRODUCTO VARCHAR(20),
    IN CANTIDAD INT,
    IN VALOR FLOAT
)
BEGIN
    DECLARE PEDIDO INT;
    DECLARE PRODUCTO_ID INT;
    SET PEDIDO=(SELECT MAX(ID) FROM PEDIDOS);
    SET PRODUCTO_ID=(SELECT ID FROM PRODUCTOS WHERE NOMBRE=PRODUCTO); 
    INSERT INTO DETALLES_PEDIDO(PEDIDO_ID,PRODUCTO_ID,CANTIDAD,VALOR,SUBTOTAL,HABILITADO)VALUES(PEDIDO,PRODUCTO_ID,CANTIDAD,VALOR,CANTIDAD*VALOR,1);
END ;;
DELIMITER ;

--PROCEDIMIENTO PARA MOSTRAR DETALLE PEDIDO
DELIMITER ;;
CREATE PROCEDURE `MOSTRAR_DETALLE_PEDIDO`(IN COD_PEDIDO INT)
BEGIN
SELECT PRODUCTOS.NOMBRE,DETALLES_PEDIDO.ID,DETALLES_PEDIDO.PEDIDO_ID,DETALLES_PEDIDO.CANTIDAD,DETALLES_PEDIDO.VALOR,DETALLES_PEDIDO.SUBTOTAL FROM DETALLES_PEDIDO INNER JOIN PRODUCTOS ON DETALLES_PEDIDO.PRODUCTO_ID=PRODUCTOS.ID
	WHERE DETALLES_PEDIDO.PEDIDO_ID=COD_PEDIDO AND DETALLES_PEDIDO.HABILITADO=1;
END ;;
DELIMITER ;

--ELIMINAR DETALLE PEDIDO

DELIMITER ;;
CREATE PROCEDURE `ELIMINAR_DETALLE_PEDIDO`(IN COD_DETALLE INT,IN PEDIDO_ID INT)
BEGIN
DECLARE SUBTOTALP INT;
DECLARE TOTALP INT;
DECLARE TOT INT;
SET SUBTOTALP=(SELECT SUBTOTAL FROM DETALLES_PEDIDO WHERE ID=COD_DETALLE);
SET TOTALP=(SELECT TOTAL FROM PEDIDOS WHERE ID=PEDIDO_ID);	
UPDATE DETALLES_PEDIDO SET HABILITADO=0 WHERE ID=COD_DETALLE;	
UPDATE PEDIDOS SET TOTAL=TOTALP-SUBTOTALP WHERE ID=PEDIDO_ID;
SET TOT=(SELECT TOTAL FROM PEDIDOS WHERE ID=PEDIDO_ID);
if TOT=0 THEN
UPDATE PEDIDOS SET HABILITADO=0 WHERE ID=PEDIDO_ID;
END if;
END ;;
DELIMITER ;
--EDITAR CANTIDAD DETALLE PEDIDO

DELIMITER ;;
CREATE PROCEDURE `Editar_Cantidad`(IN COD_DETALLE INT,IN PEDIDO_ID INT,IN CANTIDAD INT)
BEGIN
DECLARE SUBTOTALP INT;
DECLARE TOTALP INT;
DECLARE TOT INT;
SET SUBTOTALP=(SELECT SUBTOTAL FROM DETALLES_PEDIDO WHERE ID=COD_DETALLE);
SET TOTALP=(SELECT TOTAL FROM PEDIDOS WHERE ID=PEDIDO_ID);
UPDATE DETALLES_PEDIDO SET HABILITADO=0 WHERE ID=COD_DETALLE;
UPDATE PEDIDOS SET TOTAL=TOTALP-SUBTOTALP WHERE ID=PEDIDO_ID;
SET TOT=(SELECT TOTAL FROM PEDIDOS WHERE ID=PEDIDO_ID);
if TOT=0 THEN
UPDATE PEDIDOS SET HABILITADO=0 WHERE ID=PEDIDO_ID;
END if;
END ;;
DELIMITER ;


